Enhance Docker build workflow with Cosign integration for image signing and verification

diff --git a/.github/workflows/build.docker.images.yml b/.github/workflows/build.docker.images.yml
--- a/.github/workflows/build.docker.images.yml
+++ b/.github/workflows/build.docker.images.yml
@@ -91,6 +91,7 @@ jobs:
 
       - name: Build and push
         uses: docker/build-push-action@53b7df96c91f9c12dcc8a07bcb9ccacbed38856a  # v7.3.0
+        id: build        
         with:
           context: .
           file: ./Dockerfile
@@ -102,3 +103,65 @@ jobs:
           platforms: ${{ env.REGISTRY_PLATFORMS }}
           cache-from: type=registry,ref=${{ env.REGISTRY_ACCOUNT }}/${{ env.REGISTRY_REPO }}:${{ env.REGISTRY_REPO_TAG_CACHE_NAME }}
           cache-to: type=registry,ref=${{ env.REGISTRY_ACCOUNT }}/${{ env.REGISTRY_REPO }}:${{ env.REGISTRY_REPO_TAG_CACHE_NAME }},mode=max
+
+      - name: Install Cosign
+        uses: sigstore/cosign-installer@6f9f17788090df1f26f669e9d70d6ae9567deba6  # v4.1.2
+
+      - name: Show Cosign version
+        shell: bash      
+        run: |
+          cosign version
+
+      - name: Sign docker image with a key
+        shell: bash
+        run: |                
+          cosign sign \
+            --new-bundle-format=true \
+            --use-signing-config=false \
+            --yes \
+            --key env://COSIGN_PRIVATE_KEY ${{ env.REGISTRY }}/${{ steps.tags.outputs.docker }}:@${{ steps.build.outputs.digest }}
+        env:
+          COSIGN_PRIVATE_KEY: ${{ secrets.cosign_private_key }}
+          COSIGN_PASSWORD: ${{ secrets.cosign_password }}
+
+      - name: Verify image signature
+        shell: bash
+        run: |
+          set -euo pipefail
+
+          IMAGE="${{ env.REGISTRY }}/${{ steps.tags.outputs.docker }}:@${{ steps.build.outputs.digest }}"
+
+          for i in {1..12}; do
+            echo "Verification attempt ${i}/12..."
+
+            if cosign verify \
+                --key cosign.pub \
+                --output text \
+                "${IMAGE}"; then
+              echo "Signature verified."
+
+              exit 0
+            fi
+
+            echo "Signature not yet available. Waiting 5 seconds..."
+            sleep 5
+          done
+
+          echo "ERROR: Signature could not be verified after 60 seconds."
+          exit 1
+
+      - name: Show Cosign artifact tree
+        shell: bash
+        run: |
+          cosign tree ${{ env.REGISTRY }}/${{ steps.tags.outputs.docker }}:@${{ steps.build.outputs.digest }}
+
+
+      - name: Promote image to latest
+        if: github.event.release.tag_name != ''
+        shell: bash
+        run: |
+          # Create or update the "latest" tag to point to the newly released image version.
+          # This operation updates the manifest in the registry and preserves all platform variants.
+          docker buildx imagetools create \
+            -t ${{ env.REGISTRY_ACCOUNT }}/${{ env.REGISTRY_REPO }}:latest \
+            ${{ steps.tags.outputs.docker }}
